# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'HelloWorldApp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for HelloWorldApp
  pod 'Firebase/Core', '~> 5.15.0'
  pod 'Firebase/Auth', '~> 5.15.0'
  pod 'Firebase/Database', '~> 5.15.0'

  target 'HelloWorldAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'HelloWorldApp-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for HelloWorldApp-tvOS

  target 'HelloWorldApp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
